name: Tests

on:
  push:
    branches:
      - rustlang/fundamentals/week1
      
jobs:
  test:
    if: github.ref == 'refs/heads/rustlang/fundamentals/week1'
    runs-on: ubuntu-latest
    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ./rust-service
    - name: Test algo
      working-directory: ./rust-service/rustlang
      run: cargo test
